
# config file containing parameters
configfile: "config/config.yml"

# workflow rules
include: "rules/perform_diff_expr_tests.smk"
include: "rules/perform_power_simulations.smk"
include: "rules/create_input_and_output.smk"
include: "rules/create_encode_output.smk"
include: "rules/create_candidate_cres.smk"
include: "rules/gasperini_dataset.smk"
include: "rules/tapseq_dataset.smk"
include: "rules/nasser_dataset.smk"
include: "rules/hcrflowfish_dataset.smk"
include: "rules/hct116_dataset.smk"
include: "rules/additional_analyses.smk"  # optional analyses to estimate guide variability

# perform all differential expression and power analyses to create main output files
rule all:
  input:
    de_tests = expand("results/{sample}/diff_expr_{method}_{strategy}.html", 
      sample = ["Gasperini2019", "TAPseq", "TAPseqChr8", "TAPseqChr11"], method = "MAST",
      strategy = "perCRE"),
    power_analysis = expand("results/{sample}/power_analysis_{sd}gStd_{method}_{strategy}.html",
      sample = ["Gasperini2019", "TAPseq", "TAPseqChr8", "TAPseqChr11"], sd = 0.13, method = "MAST",
      strategy = "perCRE")

# create all output files for ENCODE
rule encode_files:
  input:
    expand("results/ENCODE/ENCODE_{sample}_{sd}gStd_MAST_perCRE_GRCh38.tsv.gz",
      sample = ["Gasperini2019", "TAPseq"],  sd = 0.13),
    expand("results/ENCODE/EPCrisprBenchmark/EPCrisprBenchmark_{sample}_{sd}gStd_{pwr}pwrAt{es}effect_GRCh38.tsv.gz",
      sample = ["Gasperini2019", "TAPseq"], sd = 0.13, pwr = 0.8, es = 15),
    "results/ENCODE/EPCrisprBenchmark/EPCrisprBenchmark_Nasser2021_K562_GRCh38.tsv.gz",
    "results/ENCODE/EPCrisprBenchmark/EPCrisprBenchmark_Nasser2021_otherCellTypes_GRCh38.tsv.gz",
    "results/ENCODE/EPCrisprBenchmark/EPCrisprBenchmark_HCRFlowFISH_perCRE_GRCh38.tsv.gz",
    "results/ENCODE/EPCrisprBenchmark/EPCrisprBenchmark_HCT116_FlowFISH_0.8pwrAt25effect_GRCh38.tsv.gz"
    "results/ENCODE/ENCODE_CombinedData_GRCh38.tsv.gz",
    "results/ENCODE/EPCrisprBenchmark/EPCrisprBenchmark_CombinedData_GRCh38.tsv.gz"    

# auxillary rules, remove once done ----------------------------------------------------------------

# perform all DE tests
rule all_de_tests:
  input:
    expand("results/{sample}/diff_expr/output_MAST_{pert_level}.tsv.gz",
      sample = ["Gasperini2019", "TAPseq", "TAPseqChr8", "TAPseqChr11"],
      pert_level = ["perCRE", "perGRNA"])
      
# perform all power simulations
rule all_pwr_sims:
  input:
    expand("results/{sample}/power_sim/power_{effect_size}_{sd}gStd_MAST_perCRE.tsv.gz",
      sample = ["Gasperini2019", "TAPseq", "TAPseqChr8", "TAPseqChr11"],
      effect_size = config["power_simulations"]["effect_sizes"], sd = 0.13)
