
# config file containing parameters
configfile: "config/config.yml"

# workflow rules
include: "rules/create_gasperini_input.smk"
include: "rules/perform_diff_expr.smk"
include: "rules/perform_power_simulations.smk"
include: "rules/create_output.smk"
include: "rules/additional_analyses.smk"

# perform all analyses
rule all:
  input:
    expand("results/{sample}/power_analysis_{sd}gStd_MAST_perCRE.html",
      sample = "Gasperini2019", sd = "0.1")

# perform all DE tests
rule all_de_tests:
  input:
    expand("results/Gasperini2019/diff_expr/output_MAST_{pert_level}.csv.gz",
           pert_level = ["perCRE", "perGRNA"])

# generate all input for power simulations
rule pwr_input:
  input:
    expand("resources/Gasperini2019/perturb_sce_disp.{chr}.rds",
    chr = ["chr" + str(i)  for i in [*range(1, 23), "X"]])

# perform all power simulations
rule all_pwr_sims:
  input:
    expand("results/Gasperini2019/power_sim/power_{effect_size}_0.1gStd_MAST_perCRE.csv.gz",
      effect_size = config["power_simulations"]["effect_sizes"])
