
# urls to download data
download_urls:
  gasperini_cds: "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE120nnn/GSE120861/suppl/GSE120861_at_scale_screen.cds.rds.gz"
  gencode.v26lift37: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/GRCh37_mapping/gencode.v26lift37.annotation.gtf.gz"
  gencode.v26: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/gencode.v26.annotation.gtf.gz"
  gencode.v29: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz"
  liftover_chain: "https://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz"
  Nasser2021:
    K562: "https://raw.githubusercontent.com/EngreitzLab/ABC-GWAS-Paper/main/comparePredictorsToCRISPRData/comparisonRuns/K562-only/experimentalData/experimentalData.K562-only.txt"
    allCellTypes: "https://raw.githubusercontent.com/EngreitzLab/ABC-GWAS-Paper/main/comparePredictorsToCRISPRData/comparisonRuns/AllCellTypes-ABC_comparison/experimentalData/experimentalData.AllCellTypes.txt"
  RefSeq_tss: "https://raw.githubusercontent.com/broadinstitute/ABC-Enhancer-Gene-Prediction/master/reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.TSS500bp.bed"

# DNase-seq bam files for candidate CREs
dnase_bam:
  ENCFF030DCL:
    url:  "https://www.encodeproject.org/files/ENCFF030DCL/@@download/ENCFF030DCL.bam"
    chrs: "resources/hg19_chr_sizes"
  ENCFF205FNC:
    url:  "https://www.encodeproject.org/files/ENCFF205FNC/@@download/ENCFF205FNC.bam"
    chrs: "resources/GRCh38_EBV.no_alt.chrom.sizes.tsv"

# specify which samples should be split by chromosome when performing DE tests and power simulations
split_by_chr:
  Gasperini2019: True
  TAPseqChr8: False
  TAPseqChr11: False

# parameters for differential expression tests to map perturbations to target genes
diff_expr:
  umis_per_cell:
    Gasperini2019:  [1, 75000]
    TAPseqChr8:  [1, 6000]
    TAPseqChr11: [1, 6000]
  min_cells:
    perGRNA: 15
    perCRE:  25
  max_dist:
    Gasperini2019: 2e6
    TAPseqChr8: NULL
    TAPseqChr11: NULL
  formula: "~pert+scale(detected_genes)"
  n_ctrl:
     Gasperini2019: 5000
     TAPseqChr8: 3500
     TAPseqChr11: 3500
  cell_batches:
     Gasperini2019: NULL
     TAPseqChr8:  "lane_barcodes"
     TAPseqChr11: "lane_barcodes"
  padj_method: "fdr"
  padj_threshold: 0.05
  threads: 1

# parameters for power simulations to estimate statistical power for every perturbation-gene pair
power_simulations:
  effect_sizes: [0.1, 0.15, 0.2, 0.25, 0.5]
  remove_genes:
    Gasperini2019: NULL
    TAPseqChr8: "HBE1"
    TAPseqChr11: "HBE1"
  size_factors: "poscounts"
  fit_type: "parametric"
  norm:
    Gasperini2019: "sim_nonpert"
    TAPseqChr8:  "real"
    TAPseqChr11: "real"
  rep: 20
  threads: 1

# parameters to create output in ENCODE and EP benchmarking format
encode_datasets:
  ignore_transcripts:
    Gasperini2019: NULL
    TAPseq: ["ENST00000380252.6", "ENST00000292896.3", "ENST00000380237.5"]
  dist_to_TSS: [1000, 1e6]
  annot:
    Gasperini2019: "resources/gencode.v26lift37.annotation.gtf.gz"
    TAPseq: "resources/gencode.v29.annotation.gtf.gz"
  genome_build:
    Gasperini2019: "hg19"
    TAPseq: "GRCh38"
  
# additional metadata per experiment
metadata:
  Gasperini2019:
    cell_type: "K562"
    reference: "Gasperini et al., 2019"
    gene_ids: "ensembl"
    tss_ctrl_tag: "TSSCtrl"
  TAPseq:
    cell_type: "K562"
    reference: "Schraivogel et al., 2020"
    gene_ids: "symbol"
    tss_ctrl_tag: "TSSCtrl"

# additional parameters to process TAP-seq dataset
process_tapseq:
  remove_lanes:
    TAPseqChr8:  []
    TAPseqChr11: ["CATCGACC"]
    
# re-format Nasser at al., 2021 CRISPR data --------------------------------------------------------
Nasser2021:
  subsets:
    otherCellTypes: ["NCCIT", "PrimaryHepatocytes", "BJAB", "Jurkat", "THP1", "GM12878", "LNCAP"]
    
# re-process HCR-FlowFISH data ---------------------------------------------------------------------

# minimum guide count filters for each locus and replicate. first number is rep 1, second rep 2
min_guide_counts:
  LMO2: [10, 10]
  NMU: [100, 100]
  FADS1: [100, 50]
  MEF2C: [20, 20]
  GATA1: [50, 50]
  FADS3: [200, 50]
  ERP29: [30, 20]
  HDAC6: [10, 10]
  FEN1: [50, 50]
  FADS2: [250, 100]
  CD164: [50, 20]
  MYC: [25, 50]
  PVT1: [20, 10]
  CAPRIN1: [12, 10]
  HBG2: [100, 100]
  CAT: [12, 10]
  MYB: [100, 20]
  HBG1: [100, 100]
  HBS1L: [100, 50]
  HBE1: [120, 50]

# parameters for identifying enhancer-gene interactions
score_enhancers:
  mineffectsize: 0
  minguides: 10
  fdr: 0.05
